export const tourismDestinations = {
    santaCruz: [
        {
            title: 'Calafate',
            province: 'Santa Cruz',
            imgLink: '',
            imgDescription: '',
            description: 'glaciares, trekking, navegación',
        },
        {
            title: 'El Chaltén',
            province: 'Santa Cruz',
            imgLink: '',
            imgDescription: '',
            description: 'escalada, trekking, vistas panorámicas',
        },
        {
            title: 'Cabo Vírgenes',
            province: 'Santa Cruz',
            imgLink: '',
            imgDescription: '',
            description: 'turismo científico, offroad, faros históricos',
        },
    ],
    buenosAires: [
        {
            title: 'Sierra de la Ventana',
            province: 'Buenos Aires',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, escalada, avistaje de fauna',
        },
        {
            title: 'Mar del Plata',
            province: 'Buenos Aires',
            imgLink: '',
            imgDescription: '',
            description: 'surf, offroad, turismo costero',
        },
        {
            title: 'Tandil',
            province: 'Buenos Aires',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, aventura, naturaleza',
        },
    ],
    cordoba: [
        {
            title: 'Villa Carlos Paz',
            province: 'Córdoba',
            imgLink: '',
            imgDescription: '',
            description: 'turismo aventura, navegación, trekking',
        },
        {
            title: 'La Cumbrecita',
            province: 'Córdoba',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, escalada, vistas naturales',
        },
        {
            title: 'Capilla del Monte',
            province: 'Córdoba',
            imgLink: '',
            imgDescription: '',
            description: 'turismo místico, trekking, escalada',
        },
    ],

    mendoza: [
        {
            title: 'Potrerillos',
            province: 'Mendoza',
            imgLink: '',
            imgDescription: '',
            description: 'navegación, rafting, vistas montañosas',
        },
        {
            title: 'Malargüe',
            province: 'Mendoza',
            imgLink: '',
            imgDescription: '',
            description: 'volcanes, espeleología, turismo científico',
        },
        {
            title: 'Cacheuta',
            province: 'Mendoza',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, aguas termales, relax',
        },
    ],
    neuquen: [
        {
            title: 'Villa La Angostura',
            province: 'Neuquén',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, navegación, paisajes andinos',
        },
        {
            title: 'San Martín de los Andes',
            province: 'Neuquén',
            imgLink: '',
            imgDescription: '',
            description: 'pesca, trekking, turismo aventura',
        },
        {
            title: 'Aluminé',
            province: 'Neuquén',
            imgLink: '',
            imgDescription: '',
            description: 'rafting, trekking, naturaleza',
        },
    ],
    rioNegro: [
        {
            title: 'San Carlos de Bariloche',
            province: 'Río Negro',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, esquí, navegación',
        },
        {
            title: 'El Bolsón',
            province: 'Río Negro',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, escalada, naturaleza',
        },
        {
            title: 'Las Grutas',
            province: 'Río Negro',
            imgLink: '',
            imgDescription: '',
            description: 'turismo costero, snorkeling, offroad',
        },
    ],

    chubut: [
        {
            title: 'Puerto Madryn',
            province: 'Chubut',
            imgLink: '',
            imgDescription: '',
            description: 'avistaje de fauna, turismo científico, buceo',
        },
        {
            title: 'Esquel',
            province: 'Chubut',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, paisajes montañosos, turismo ferroviario',
        },
        {
            title: 'Lago Puelo',
            province: 'Chubut',
            imgLink: '',
            imgDescription: '',
            description: 'navegación, senderismo, turismo aventura',
        },
    ],

    tierraDelFuego: [
        {
            title: 'Ushuaia',
            province: 'Tierra del Fuego',
            imgLink: '',
            imgDescription: '',
            description: 'glaciares, trekking, navegación antártica',
        },
        {
            title: 'Tolhuin',
            province: 'Tierra del Fuego',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, vistas panorámicas, naturaleza',
        },
        {
            title: 'Cabo San Pablo',
            province: 'Tierra del Fuego',
            imgLink: '',
            imgDescription: '',
            description: 'offroad, faros históricos, paisajes costeros',
        },
    ],

    salta: [
        {
            title: 'Cafayate',
            province: 'Salta',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, paisajes de quebradas, viñedos',
        },
        {
            title: 'Cachi',
            province: 'Salta',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, cultura, vistas montañosas',
        },
        {
            title: 'San Antonio de los Cobres',
            province: 'Salta',
            imgLink: '',
            imgDescription: '',
            description: 'offroad, turismo ferroviario, paisajes áridos',
        },
    ],

    jujuy: [
        {
            title: 'Purmamarca',
            province: 'Jujuy',
            imgLink: '',
            imgDescription: '',
            description: 'cerro de los siete colores, trekking, cultura',
        },
        {
            title: 'Tilcara',
            province: 'Jujuy',
            imgLink: '',
            imgDescription: '',
            description: 'arqueología, senderismo, cultura andina',
        },
        {
            title: 'Humahuaca',
            province: 'Jujuy',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, cultura, paisajes quebradeños',
        },
    ],
    tucuman: [
        {
            title: 'Tafí del Valle',
            province: 'Tucumán',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, vistas montañosas, cultura',
        },
        {
            title: 'Cerro San Javier',
            province: 'Tucumán',
            imgLink: '',
            imgDescription: '',
            description: 'parapente, trekking, naturaleza',
        },
        {
            title: 'Amaicha del Valle',
            province: 'Tucumán',
            imgLink: '',
            imgDescription: '',
            description: 'cultura, trekking, vistas panorámicas',
        },
    ],
    entreRios: [
        {
            title: 'Colón',
            province: 'Entre Ríos',
            imgLink: '',
            imgDescription: '',
            description: 'playas, turismo costero, naturaleza',
        },
        {
            title: 'Federación',
            province: 'Entre Ríos',
            imgLink: '',
            imgDescription: '',
            description: 'aguas termales, turismo aventura, naturaleza',
        },
        {
            title: 'Paraná',
            province: 'Entre Ríos',
            imgLink: '',
            imgDescription: '',
            description: 'navegación, pesca, turismo fluvial',
        },
    ],

    misiones: [
        {
            title: 'Cataratas del Iguazú',
            province: 'Misiones',
            imgLink: '',
            imgDescription: '',
            description: 'cataratas, trekking, naturaleza',
        },
        {
            title: 'San Ignacio',
            province: 'Misiones',
            imgLink: '',
            imgDescription: '',
            description: 'ruinas jesuíticas, cultura, historia',
        },
        {
            title: 'Salto Encantado',
            province: 'Misiones',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, cascadas, naturaleza',
        },
    ],

    sanLuis: [
        {
            title: 'Merlo',
            province: 'San Luis',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, parapente, turismo aventura',
        },
        {
            title: 'Potrero de los Funes',
            province: 'San Luis',
            imgLink: '',
            imgDescription: '',
            description: 'navegación, trekking, vistas naturales',
        },
        {
            title: 'Sierra de las Quijadas',
            province: 'San Luis',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, paisajes desérticos, arqueología',
        },
    ],

    laRioja: [
        {
            title: 'Parque Nacional Talampaya',
            province: 'La Rioja',
            imgLink: '',
            imgDescription: '',
            description: 'cánones, turismo científico, trekking',
        },
        {
            title: 'Chilecito',
            province: 'La Rioja',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, cultura, turismo ferroviario',
        },
        {
            title: 'Villa Unión',
            province: 'La Rioja',
            imgLink: '',
            imgDescription: '',
            description: 'circuitos turísticos, naturaleza, cultura',
        },
    ],

    catamarca: [
        {
            title: 'Antinaco',
            province: 'Catamarca',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, turismo arqueológico, vistas montañosas',
        },
        {
            title: 'Fiambalá',
            province: 'Catamarca',
            imgLink: '',
            imgDescription: '',
            description: 'aguas termales, offroad, trekking',
        },
        {
            title: 'Belén',
            province: 'Catamarca',
            imgLink: '',
            imgDescription: '',
            description: 'artesanía, trekking, paisajes áridos',
        },
    ],

    corrientes: [
        {
            title: 'Esteros del Iberá',
            province: 'Corrientes',
            imgLink: '',
            imgDescription: '',
            description: 'avistaje de fauna, navegación, senderismo',
        },
        {
            title: 'Goya',
            province: 'Corrientes',
            imgLink: '',
            imgDescription: '',
            description: 'pesca, turismo fluvial, naturaleza',
        },
        {
            title: 'Itatí',
            province: 'Corrientes',
            imgLink: '',
            imgDescription: '',
            description: 'turismo religioso, vistas naturales, cultura',
        },
    ],
    formosa: [
        {
            title: 'Laguna Yema',
            province: 'Formosa',
            imgLink: '',
            imgDescription: '',
            description: 'pesca, avistaje de fauna, turismo fluvial',
        },
        {
            title: 'Formosa Capital',
            province: 'Formosa',
            imgLink: '',
            imgDescription: '',
            description: 'navegación, cultura, turismo urbano',
        },
        {
            title: 'Berrondo',
            province: 'Formosa',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, naturaleza, turismo rural',
        },
    ],

    chaco: [
        {
            title: 'Resistencia',
            province: 'Chaco',
            imgLink: '',
            imgDescription: '',
            description: 'esculturas urbanas, turismo cultural, naturaleza',
        },
        {
            title: 'El Impenetrable',
            province: 'Chaco',
            imgLink: '',
            imgDescription: '',
            description: 'trekking, avistaje de fauna, naturaleza',
        },
        {
            title: 'Presidencia Roque Sáenz Peña',
            province: 'Chaco',
            imgLink: '',
            imgDescription: '',
            description: 'aguas termales, turismo rural, cultura',
        },
    ],
    santaFe: [
        {
            title: 'Rosario',
            province: 'Santa Fe',
            imgLink: '',
            imgDescription: '',
            description: 'turismo urbano, navegación, pesca',
        },
        {
            title: 'Santa Fe Capital',
            province: 'Santa Fe',
            imgLink: '',
            imgDescription: '',
            description: 'turismo histórico, navegación, cultura',
        },
        {
            title: 'Reconquista',
            province: 'Santa Fe',
            imgLink: '',
            imgDescription: '',
            description: 'pesca, turismo rural, senderismo',
        },
    ],
    santiagoDelEstero: [
        {
            title: 'Termas de Río Hondo',
            province: 'Santiago del Estero',
            imgLink: '',
            imgDescription: '',
            description: 'aguas termales, relax, turismo urbano',
        },
        {
            title: 'Añatuya',
            province: 'Santiago del Estero',
            imgLink: '',
            imgDescription: '',
            description: 'turismo rural, cultura, naturaleza',
        },
        {
            title: 'Santiago del Estero Capital',
            province: 'Santiago del Estero',
            imgLink: '',
            imgDescription: '',
            description: 'historia, cultura, turismo urbano',
        }
    ],
    sanJuan: [
        {
            title: 'Valle de la Luna (Ischigualasto)',
            province: 'San Juan',
            imgLink: 'https://www.locoporlasmillas.com/wp-content/uploads/2022/07/20210820_153836-1536x864.jpg',
            imgDescription: '',
            description: 'geología, turismo científico, trekking',
        },
        {
            title: 'Barreal',
            province: 'San Juan',
            imgLink: 'https://www.welcomeargentina.com/paseos/visita-el-barreal/barreal-3.jpg',
            imgDescription: '',
            description: 'astroturismo, trekking, paisajes montañosos',
        },
        {
            title: 'Calingasta',
            province: 'San Juan',
            imgLink: '',
            imgDescription: '',
            description: 'offroad, vistas naturales, turismo rural',
        },
    ],
    laPampa: [
        {
            title: 'Parque Luro',
            province: 'La Pampa',
            imgLink: '',
            imgDescription: '',
            description: 'avistaje de fauna, senderismo, turismo rural',
        },
        {
            title: 'Santa Rosa',
            province: 'La Pampa',
            imgLink: '',
            imgDescription: '',
            description: 'pesca, turismo urbano, naturaleza',
        },
        {
            title: 'General Acha',
            province: 'La Pampa',
            imgLink: '',
            imgDescription: '',
            description: 'senderismo, cultura, paisajes áridos',
        },
    ],
};
