export const tourismDestinations = {
    santaCruz: [
        {
            title: 'Calafate',
            province: 'Santa Cruz',
            imgLink: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxHj1-vgirl-cSnT8guyyP12tEqRcw01HFY0fjT6BEkCrb8U2TD0t_RrFooc3FWRplSSThooz6UWCuUYRsnjl2hxGoftX_VNh0ARAikHZFuozLogqOFz1_u3_foGp-cZ5aZeHzNHIV4A0/s640/perito+moreno+04.jpg',
            imgDescription: 'Glaciar Perito Moreno',
            description: 'glaciares, trekking, navegación',
        },
        {
            title: 'El Chaltén',
            province: 'Santa Cruz',
            imgLink: 'https://www.viagensecaminhos.com/wp-content/uploads/2015/02/laguna-los-tres-el-chalten.jpg',
            imgDescription: 'Laguna de los TreS',
            description: 'escalada, trekking, vistas panorámicas',
        },
        {
            title: 'Cabo Vírgenes',
            province: 'Santa Cruz',
            imgLink: 'https://www.nubesviajeras.com/wp-content/uploads/2015/05/faro-cabo-v%C3%ADrgenes-900x600.jpg',
            imgDescription: 'Faro del Cabo',
            description: 'turismo científico, offroad, faros históricos',
        },
    ],
    buenosAires: [
        {
            title: 'Sierra de la Ventana',
            province: 'Buenos Aires',
            imgLink: 'https://i.pinimg.com/originals/e4/c3/63/e4c363939a238347f679609140c75e37.jpg',
            imgDescription: 'Río Las Golfas',
            description: 'trekking, escalada, avistaje de fauna',
        },
        {
            title: 'Mar del Plata',
            province: 'Buenos Aires',
            imgLink: 'https://insidemdp.com.ar/wp-content/uploads/2022/11/playa-chica-mar-del-plata.jpg',
            imgDescription: 'Playa Chica',
            description: 'surf, offroad, turismo costero',
        },
        {
            title: 'Tandil',
            province: 'Buenos Aires',
            imgLink: 'http://refugiodelangel.com.ar/web/blog/wp-content/uploads/2014/02/don-quijote-y-sancho-en-tandil-150x150.jpg',
            imgDescription: 'Cerro La Virgen',
            description: 'trekking, aventura, naturaleza',
        },
    ],
    cordoba: [
        {
            title: 'Villa Carlos Paz',
            province: 'Córdoba',
            imgLink: 'https://respiroviajes.com/wp-content/uploads/2020/05/que-hacer-en-carlos-paz-4-1.jpg',
            imgDescription: 'Lago San Roque',
            description: 'turismo aventura, navegación, trekking',
        },
        {
            title: 'La Cumbrecita',
            province: 'Córdoba',
            imgLink: 'https://turismo-en-argentina.com/wp-content/uploads/2018/01/la_cumbrecita-1024x550.jpg',
            imgDescription: 'Arquitectura Alpina',
            description: 'trekking, escalada, vistas naturales',
        },
        {
            title: 'Capilla del Monte',
            province: 'Córdoba',
            imgLink: 'https://tripin.travel/wp-content/uploads/2016/09/los-paredones-cordoba-youtube-1024x576.jpg.webp',
            imgDescription: 'Los Paredones',
            description: 'turismo místico, trekking, escalada',
        },
    ],

    mendoza: [
        {
            title: 'Potrerillos',
            province: 'Mendoza',
            imgLink: 'https://www.mendozaturismo.com.ar/img/900/potrerillos-mendoza.jpg',
            imgDescription: 'Lago Potrerillos',
            description: 'navegación, rafting, vistas montañosas',
        },
        {
            title: 'Malargüe',
            province: 'Mendoza',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/27292187221_a72f44899b_k-1-1536x1024.webp',
            imgDescription: 'Pozo de Las Ánimas',
            description: 'volcanes, espeleología, turismo científico',
        },
        {
            title: 'Cacheuta',
            province: 'Mendoza',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/mountain-g6ff4de78a_1280-768x512.jpg',
            imgDescription: 'Laguna y cerros nevados',
            description: 'trekking, aguas termales, relax',
        },
    ],
    neuquen: [
        {
            title: 'Villa La Angostura',
            province: 'Neuquén',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/20211031_122012_HDR-scaled-e1664908323541-768x637.jpg',
            imgDescription: 'Villa a orillas del lago',
            description: 'trekking, navegación, paisajes andinos',
        },
        {
            title: 'San Martín de los Andes',
            province: 'Neuquén',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2023/05/vista-santiago-compostela-768x512.jpg',
            imgDescription: 'Iglesia Santiago de Compostela',
            description: 'pesca, trekking, turismo aventura',
        },
        {
            title: 'Aluminé',
            province: 'Neuquén',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/20211105_164227_HDR-scaled-e1668101468672-768x616.jpg',
            imgDescription: 'Muelle a la vera del lago',
            description: 'rafting, trekking, naturaleza',
        },
    ],
    rioNegro: [
        {
            title: 'San Carlos de Bariloche',
            province: 'Río Negro',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/san-carlos-bariloche-is-city-in-the-argentinian-province-of-rio-negro-view-of-the-lake-and-the-city-of-bariloche-768x512.jpg',
            imgDescription: 'Ciudad de Bariloche',
            description: 'trekking, esquí, navegación',
        },
        {
            title: 'El Bolsón',
            province: 'Río Negro',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/10/20211027_122320_HDR-3-1-768x768.jpg',
            imgDescription: 'Río El Bolsón',
            description: 'senderismo, escalada, naturaleza',
        },
        {
            title: 'Las Grutas',
            province: 'Río Negro',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2023/06/cacahuamilpa-caves-5754474_1280-1024x576.jpg',
            imgDescription: 'Cueva con petrograbados',
            description: 'turismo costero, snorkeling, offroad',
        },
    ],

    chubut: [
        {
            title: 'Puerto Madryn',
            province: 'Chubut',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/800px-Puerto_Madryn_Patagonia-768x544.jpg',
            imgDescription: 'Faro de Puerto Madryn',
            description: 'avistaje de fauna, turismo científico, buceo',
        },
        {
            title: 'Esquel',
            province: 'Chubut',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/2560px-Trochita_puente_sobre_Rio_Chico-768x512.jpeg',
            imgDescription: 'Tren patagónico',
            description: 'trekking, paisajes montañosos, turismo ferroviario',
        },
        {
            title: 'Lago Puelo',
            province: 'Chubut',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/10/800px-Puelo_Lake-768x576.jpg',
            imgDescription: 'Parque Nacional Lago Puelo',
            description: 'navegación, senderismo, turismo aventura',
        },
    ],

    tierraDelFuego: [
        {
            title: 'Ushuaia',
            province: 'Tierra del Fuego',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/06/comer-en-ushuaia-768x576.jpg',
            imgDescription: 'Pueblo de Ushuaia',
            description: 'glaciares, trekking, navegación antártica',
        },
        {
            title: 'Tolhuin',
            province: 'Tierra del Fuego',
            imgLink: 'https://www.welcomeargentina.com/paseos/city-tour-tolhuin/tolhuin-tierra-del-fuego-4.jpg',
            imgDescription: 'Kaiken Tolhuin',
            description: 'senderismo, vistas panorámicas, naturaleza',
        },
        {
            title: 'Cabo San Pablo',
            province: 'Tierra del Fuego',
            imgLink: 'https://www.patagoniaandina.com/wp-content/uploads/2023/05/cabo-san-pablo-patagonia-andina-3-1024x683.jpg',
            imgDescription: 'Faro del Cabo',
            description: 'offroad, faros históricos, paisajes costeros',
        },
    ],

    salta: [
        {
            title: 'Cafayate',
            province: 'Salta',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/01/cayafate-768x512.jpg',
            imgDescription: 'Farallones del Cafayate',
            description: 'trekking, paisajes de quebradas, viñedos',
        },
        {
            title: 'Cachi',
            province: 'Salta',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/07/800px-Cachi_Salta_Norte_Argentina-768x512.jpg',
            imgDescription: 'Achumas de altura',
            description: 'senderismo, cultura, vistas montañosas',
        },
        {
            title: 'San Antonio de los Cobres',
            province: 'Salta',
            imgLink: 'https://s3.amazonaws.com/aws.reislogger.nl/jennyenvincent/foto/2165990.jpg',
            imgDescription: 'Ruta del Cobre',
            description: 'offroad, turismo ferroviario, paisajes áridos',
        },
    ],

    jujuy: [
        {
            title: 'Purmamarca',
            province: 'Jujuy',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/01/20210517_105305_HDR-768x577.jpg',
            imgDescription: 'Cerros de colores',
            description: 'cerro de los siete colores, trekking, cultura',
        },
        {
            title: 'Tilcara',
            province: 'Jujuy',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/07/8323062082_721a01e88e_k-768x512.jpg',
            imgDescription: 'Tarde nublada de Tilcara',
            description: 'arqueología, senderismo, cultura andina',
        },
        {
            title: 'Humahuaca',
            province: 'Jujuy',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/colourful-mountains-of-quebrada-humahuaca-768x512.jpg',
            imgDescription: 'La Quebrada de Humauaca',
            description: 'trekking, cultura, paisajes quebradeños',
        },
    ],
    tucuman: [
        {
            title: 'Tafí del Valle',
            province: 'Tucumán',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/07/Tafi_del_Valle_-_postal-768x512.jpg',
            imgDescription: 'Paisaje de sierra pampeana',
            description: 'senderismo, vistas montañosas, cultura',
        },
        {
            title: 'Cerro San Javier',
            province: 'Tucumán',
            imgLink: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjiIu5duOuH8V8CJWR4enJQgQNSGGnEgWdkRoM6_Iko5J8zHfwsKlq1WoIyYbQ0oYs5boNmO1SyBMp7KiJh9boZgXOr4X2eq8RKV_vf06BL81W8QUV_dz2CEIzPcJ11NnP90JvhLjek3w/s1600/Cerro-San-Javier-Parapente.jpg',
            imgDescription: 'Vista al pueblo desde el cerro.',
            description: 'parapente, trekking, naturaleza',
        },
        {
            title: 'Amaicha del Valle',
            province: 'Tucumán',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/20210515_141000_HDR-768x577.jpg',
            imgDescription: 'Colorido en la serranía',
            description: 'cultura, trekking, vistas panorámicas',
        },
    ],
    entreRios: [
        {
            title: 'Colón',
            province: 'Entre Ríos',
            imgLink: 'http://www.termasdecolon.com.ar/util/img/galeria/01.jpg',
            imgDescription: 'Termas',
            description: 'playas, turismo costero, naturaleza',
        },
        {
            title: 'Federación',
            province: 'Entre Ríos',
            imgLink: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCspnrIjcCqEdHYcF3eq0dzL80E8Eg-89HoRWk_0o-4g9kgdxZ7LrUjisHiWq5kx1CsktqM1w2VUGIEijRcidoWOLJQCJTpvOcZCliNdyh6povXiYpXfCtfdtSR1gN5BQLTeK7IH3M3yaV/s1600-rw/17264268_627941464064400_8070539467155868643_n.jpg',
            imgDescription: 'Camping recreativo de Federación',
            description: 'aguas termales, turismo aventura, naturaleza',
        },
        {
            title: 'Paraná',
            province: 'Entre Ríos',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/Parana_Entre_Rios_Argentina_-_panoramio_467-768x432.jpg',
            imgDescription: 'El encanto de Paraná',
            description: 'navegación, pesca, turismo fluvial',
        },
    ],

    misiones: [
        {
            title: 'Cataratas del Iguazú',
            province: 'Misiones',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/01/landscape-of-big-beautiful-waterfalls-with-rainbow-cataratas-do-iguacu-768x511.jpg',
            imgDescription: 'Maravillosa vista en Puerto Iguazú',
            description: 'cataratas, trekking, naturaleza',
        },
        {
            title: 'San Ignacio',
            province: 'Misiones',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/04/Ruinas_Jesuiticas_de_San_Ignacio_Mini-768x576.jpg',
            imgDescription: 'Ruinas jesuíticas de San Ignacio',
            description: 'ruinas jesuíticas, cultura, historia',
        },
        {
            title: 'Salto Encantado',
            province: 'Misiones',
            imgLink: 'https://larutanatural.gob.ar/panel/public/uploads/rutas-naturales/originals/d6ec7349-1fed-48c5-b8ca-9786d00d7997.jpg',
            imgDescription: 'Vista desde el mirador',
            description: 'senderismo, cascadas, naturaleza',
        },
    ],

    sanLuis: [
        {
            title: 'Merlo',
            province: 'San Luis',
            imgLink: 'https://tripin.travel/wp-content/uploads/2017/12/687306-1024x683.jpg',
            imgDescription: 'Bella vista en Merlo',
            description: 'trekking, parapente, turismo aventura',
        },
        {
            title: 'Potrero de los Funes',
            province: 'San Luis',
            imgLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/75/9d/10/vista-desde-la-confiteria.jpg',
            imgDescription: 'Panorama desde la Hostería',
            description: 'navegación, trekking, vistas naturales',
        },
        {
            title: 'Sierra de las Quijadas',
            province: 'San Luis',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/04/Sierra_de_las_Quijadas_National_Park-768x512.jpg',
            imgDescription: 'Parque Nacional Las Quijadas',
            description: 'senderismo, paisajes desérticos, arqueología',
        },
    ],

    laRioja: [
        {
            title: 'Parque Nacional Talampaya',
            province: 'La Rioja',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/06/Parque_Nacional_Talampaya_4-768x576.jpg',
            imgDescription: 'Farallones en Parque Nacional Talampaya',
            description: 'cánones, turismo científico, trekking',
        },
        {
            title: 'Chilecito',
            province: 'La Rioja',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2021/07/157350188_3668491073203927_2578632192644651735_n-1-768x512.jpg',
            imgDescription: 'Turistas en Chilecito',
            description: 'trekking, cultura, turismo ferroviario',
        },
        {
            title: 'Villa Unión',
            province: 'La Rioja',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/vineyards-plantation-rioja-768x512.jpg',
            imgDescription: 'Plantaciones en Villa Unión',
            description: 'circuitos turísticos, naturaleza, cultura',
        },
    ],

    catamarca: [
        {
            title: 'Antofagasta de la Sierra',
            province: 'Catamarca',
            imgLink: 'https://st.focusedcollection.com/13735766/i/650/focused_398413198-stock-photo-huge-white-pumice-field-glitters.jpg',
            imgDescription: 'Campo de Piedra Pómez',
            description: 'trekking, turismo arqueológico, vistas montañosas',
        },
        {
            title: 'Fiambalá',
            province: 'Catamarca',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/10/Termas_de_Fiambala_-_panoramio-768x576.jpg',
            imgDescription: 'Termas de Fiambalá',
            description: 'aguas termales, offroad, trekking',
        },
        {
            title: 'Aconquija',
            province: 'Catamarca',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/06/forest-mountain-hill-adventure-valley-mountain-range-32136-pxhere.com_-768x499.jpg',
            imgDescription: 'Cuesta en Aconquija',
            description: 'artesanía, trekking, paisajes áridos',
        },
    ],

    corrientes: [
        {
            title: 'Esteros del Iberá',
            province: 'Corrientes',
            imgLink: 'https://viajerosocultos.com/wp-content/uploads/2022/11/Esteros_del_Ibera__Portal_Cambyreta_._Corrientes-768x576.jpg',
            imgDescription: 'Travesía en lancha en Esteros del Iberá',
            description: 'avistaje de fauna, navegación, senderismo',
        },
        {
            title: 'Goya',
            province: 'Corrientes',
            imgLink: 'https://www.fotopaises.com/Fotos-Paises/t500/2012/3/22/9705_1332371920.jpg',
            imgDescription: 'Balneario en Goya',
            description: 'pesca, turismo fluvial, naturaleza',
        },
        {
            title: 'Itatí',
            province: 'Corrientes',
            imgLink: 'https://www.corrienteshoy.com/galeria/fotos/2021/01/18/l_1610980799.jpg',
            imgDescription: 'Mirador de la Basílica',
            description: 'turismo religioso, vistas naturales, cultura',
        },
    ],
    formosa: [
        {
            title: 'Laguna Yema',
            province: 'Formosa',
            imgLink: 'https://live.staticflickr.com/65535/48000027767_271cd95af6_n.jpg',
            imgDescription: 'Vista aérea en Laguna Yema',
            description: 'pesca, avistaje de fauna, turismo fluvial',
        },
        {
            title: 'Formosa Capital',
            province: 'Formosa',
            imgLink: 'https://i.pinimg.com/736x/c1/df/76/c1df76d69efca1cdedb0bcfb6cd7a715.jpg',
            imgDescription: 'Costaneda formoseña',
            description: 'navegación, cultura, turismo urbano',
        },
        {
            title: 'Berrondo',
            province: 'Formosa',
            imgLink: 'https://live.staticflickr.com/65535/52255911871_fe34503875_n.jpg',
            imgDescription: 'Naturaleza en Berrondo',
            description: 'senderismo, naturaleza, turismo rural',
        },
    ],

    chaco: [
        {
            title: 'Resistencia',
            province: 'Chaco',
            imgLink: 'https://tripin.travel/wp-content/uploads/2016/07/Resistencia-PNacionalChaco04-turismo-750x500.jpg.webp',
            imgDescription: 'Paseo selvático en Resistencia',
            description: 'esculturas urbanas, turismo cultural, naturaleza',
        },
        {
            title: 'El Impenetrable',
            province: 'Chaco',
            imgLink: 'https://www.foroambiental.net/archivo/images/img_notas_abr_17/2103_el_impenetrable_rio_selva_chaco_argentina.jpg',
            imgDescription: 'Jungla subtropical en el Chaco',
            description: 'trekking, avistaje de fauna, naturaleza',
        },
        {
            title: 'Presidencia Roque Sáenz Peña',
            province: 'Chaco',
            imgLink: 'https://i0.wp.com/guialugaresturisticos.com/wp-content/uploads/2018/06/presidencia-roque-sc3a1enz-pec3b1a_museo2017-11-02.jpg?w=446&h=319&ssl=1',
            imgDescription: 'Museo Histórico Presidencia Roque Sáenz Peña',
            description: 'aguas termales, turismo rural, cultura',
        },
    ],
    santaFe: [
        {
            title: 'Rosario',
            province: 'Santa Fe',
            imgLink: 'https://cdn.britannica.com/00/161000-050-6BE21903/Rosario-bank-Argentina-Parana-River.jpg?w=400&h=300&c=crop',
            imgDescription: 'Rosario a la vera del Río Paraná',
            description: 'turismo urbano, navegación, pesca',
        },
        {
            title: 'Santa Fe Capital',
            province: 'Santa Fe',
            imgLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/50/95/7b/puente-colgante-santa.jpg?w=500&h=400&s=1',
            imgDescription: 'Puente Colgante de Santa Fé Capital',
            description: 'turismo histórico, navegación, cultura',
        },
        {
            title: 'Reconquista',
            province: 'Santa Fe',
            imgLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/a9/d7/cf/puerto-de-reconquista.jpg?w=700&h=300&s=1',
            imgDescription: 'Puerto de Reconquista',
            description: 'pesca, turismo rural, senderismo',
        },
    ],
    santiagoDelEstero: [
        {
            title: 'Termas de Río Hondo',
            province: 'Santiago del Estero',
            imgLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/73/d2/33/dique-y-embalse-de-termas.jpg?w=700&h=700&s=1',
            imgDescription: 'Balneario de Las Termas',
            description: 'aguas termales, relax, turismo urbano',
        },
        {
            title: 'Añatuya',
            province: 'Santiago del Estero',
            imgLink: 'https://www.fotopaises.com/Fotos-Paises/t500/2021/3/6/13591_1614819769.jpg',
            imgDescription: 'Viejo complejo industrial de Añatuya',
            description: 'turismo rural, cultura, naturaleza',
        },
        {
            title: 'Santiago del Estero Capital',
            province: 'Santiago del Estero',
            imgLink: 'https://www.purevacations.com/wp-content/uploads/2017/11/Santiago-del-Estero-Argentina-768x329.jpg',
            imgDescription: 'Vista aérea del centro',
            description: 'historia, cultura, turismo urbano',
        }
    ],
    sanJuan: [
        {
            title: 'Valle de la Luna (Ischigualasto)',
            province: 'San Juan',
            imgLink: 'https://www.locoporlasmillas.com/wp-content/uploads/2022/07/20210820_153836-1536x864.jpg',
            imgDescription: '',
            description: 'geología, turismo científico, trekking',
        },
        {
            title: 'Barreal',
            province: 'San Juan',
            imgLink: 'https://www.welcomeargentina.com/paseos/visita-el-barreal/barreal-3.jpg',
            imgDescription: '',
            description: 'astroturismo, trekking, paisajes montañosos',
        },
        {
            title: 'Calingasta',
            province: 'San Juan',
            imgLink: 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/01/07/99.jpg',
            imgDescription: 'Observatorio Astronómico en Calingasta',
            description: 'offroad, vistas naturales, turismo rural',
        },
    ],
    laPampa: [
        {
            title: 'Parque Luro',
            province: 'La Pampa',
            imgLink: 'https://voydeviaje.lavoz.com.ar/resizer/MTDBew6s_ahFVuagp3oGONw1-_8=/0x0:0x0/980x640/filters:quality(80):format(webp)/cloudfront-us-east-1.images.arcpublishing.com/grupoclarin/XC74B4POFZAQVLYKFPY4TWKK5A.jpg',
            imgDescription: 'Parque Nacional de Luro',
            description: 'avistaje de fauna, senderismo, turismo rural',
        },
        {
            title: 'Santa Rosa',
            province: 'La Pampa',
            imgLink: 'https://www.welcomeargentina.com/paseos/ciudad_srosa/santa-rosa-1.jpg',
            imgDescription: 'Club Guardia del Monte',
            description: 'pesca, turismo urbano, naturaleza',
        },
        {
            title: 'General Acha',
            province: 'La Pampa',
            imgLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/27/41/30/posada-san-antonio-de.jpg',
            imgDescription: 'Estancias en General Acha',
            description: 'senderismo, cultura, paisajes áridos',
        },
    ],
};
